version: "3.1"
services:
  database:
    image: mariadb:10.1
    container_name: mysite-mariadb
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=silverstripe
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "8083:3306"
  web:
    build: .
    container_name: ws-weta
    volumes:
      - /Users/nad/workspace/silverstripe-code:/var/www/html
      - ./bin/composer:/usr/local/bin/composer
    ports:
      - "8080:80"